# Data Science for Life Sciences
### My primer Notebook

Markdown: Este es mi primer notebook.
Shift + Enter

In [5]:
10 / 2

5.0

In [7]:
2+3 #Esto es texto

5

In [14]:
a=2.0
b=3
c="Hello World"

In [10]:
a+b

5

In [15]:
type(c)

str

In [22]:
print(a+b)

5.0


In [24]:
my_name="Moni"
my_age=23

In [25]:
print("Mi nombre es {} y tengo {} años.".format(my_name, my_age))

Mi nombre es Moni y tengo 23 años.


In [27]:
print("Mi nombre es", my_name,"y tengo", my_age, "años")

Mi nombre es Moni y tengo 23 años


In [37]:
my_list=[1,2,3,4,5]
type(my_list)

list

In [29]:
print(my_list)

[1, 2, 3, 4, 5]


In [34]:
for number in my_list:
  print(number)

1
2
3
4
5


In [43]:
my_names = ["Juansa", "Andrea", "Daniel", "Moni"]
print(my_names)

['Juansa', 'Andrea', 'Daniel', 'Moni']


In [47]:
import numpy as np
import pandas as pd

In [48]:
a=np.array ([1,2,3,4])
a

array([1, 2, 3, 4])

In [49]:
np.mean(a) #Promedio

2.5

In [51]:
np.std(a) #Desv. Estándar. Tienes que importar np y pd para no hacer todas las operaciones a mano

1.118033988749895

In [52]:
np.sqrt(a) #Raíz cuadrada

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [55]:
np.arange(1,21) #Imprime del 1 al 21, pero 21 no se imprime

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [58]:
np.arange(1,21,2) #Step va al final

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [59]:
np.linspace(0,10,50) #Cuenta del 1 al 10 dividido en 50

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [62]:
my_list =[0,1,2,3] #Si vuelvo a usar el nombre que creé, se sobreescribe
my_names = ["Juansa", "Andrea", "Daniel","Moni"]

for number in my_list:
  print(my_names[number])

Juansa
Andrea
Daniel
Moni


In [67]:
serie = [1,2,3,6,7]
serie_pandas = pd.Series(serie,name="my_serie")
print(serie_pandas)

0    1
1    2
2    3
3    6
4    7
Name: my_serie, dtype: int64


In [68]:
serie_df=pd.DataFrame(serie, columns=["my_serie_df"]) #dataframe
serie_df

my_serie_df
0            1
1            2
2            3
3            6
4            7

In [83]:
info={"Name":["Juansa","Andrea","Daniel","Moni"],
        "Age": [24,18,7,23]}
serie_df = pd.DataFrame(info)
serie_df

Name  Age
0  Juansa   24
1  Andrea   18
2  Daniel    7
3    Moni   23

In [77]:
netflix_url= "https://raw.githubusercontent.com/JuansaCollins/ds4ns/main/netflix_titles.csv"

In [78]:
netflix_df=pd.read_csv(netflix_url, sep=",")
netflix_df.

In [85]:
netflix_df.tail()

show_id  ...                                        description
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7785   s7786  ...  Dessert wizard Adriano Zumbo looks for the nex...
7786   s7787  ...  This documentary delves into the mystique behi...

[5 rows x 12 columns]

In [82]:
netflix_df.head()

show_id  ...                                        description
0      s1  ...  In a future where the elite inhabit an island ...
1      s2  ...  After a devastating earthquake hits Mexico Cit...
2      s3  ...  When an army recruit is found dead, his fellow...
3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

In [87]:
netflix_df.describe()

release_year
count   7787.000000
mean    2013.932580
std        8.757395
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2018.000000
max     2021.000000

In [89]:
netflix_df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [91]:
netflix_df["duration"]

0       4 Seasons
1          93 min
2          78 min
3          80 min
4         123 min
          ...    
7782       99 min
7783      111 min
7784       44 min
7785     1 Season
7786       90 min
Name: duration, Length: 7787, dtype: object

In [92]:
netflix_df.duration

0       4 Seasons
1          93 min
2          78 min
3          80 min
4         123 min
          ...    
7782       99 min
7783      111 min
7784       44 min
7785     1 Season
7786       90 min
Name: duration, Length: 7787, dtype: object

In [95]:
netflix_df["duration"].sort_values()

2451    1 Season
6515    1 Season
2102    1 Season
6510    1 Season
4571    1 Season
          ...   
4107      99 min
6496      99 min
3224      99 min
4368      99 min
3038      99 min
Name: duration, Length: 7787, dtype: object

In [96]:
netflix_df["type"]

0       TV Show
1         Movie
2         Movie
3         Movie
4         Movie
         ...   
7782      Movie
7783      Movie
7784      Movie
7785    TV Show
7786      Movie
Name: type, Length: 7787, dtype: object

In [97]:
netflix_df["type"].unique()

array(['TV Show', 'Movie'], dtype=object)

In [103]:
movies_df=netflix_df[netflix_df["type"]=="Movie"]
tvshow_df=netflix_df[netflix_df["type"]=="TV Show"]

In [101]:
movies_df

show_id  ...                                        description
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
6         s7  ...  After an awful accident, a couple admitted to ...
...      ...  ...                                                ...
7781   s7782  ...  Dragged from civilian life, a former superhero...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7786   s7787  ...  This documentary delves into the mystique behi...

[5377 rows x 12 columns]

In [104]:
tvshow_df

show_id  ...                                        description
0         s1  ...  In a future where the elite inhabit an island ...
5         s6  ...  A genetics professor experiments with a treatm...
11       s12  ...  In this dark alt-history thriller, a naïve law...
12       s13  ...  Archival video and new interviews examine Mexi...
16       s17  ...  As a psychology professor faces Alzheimer's, h...
...      ...  ...                                                ...
7767   s7768  ...  Strong-willed, middle-class Kashaf and carefre...
7775   s7776  ...  A quest for freedom and legendary treasure beg...
7777   s7778  ...  While living alone in a spooky town, a young g...
7779   s7780  ...  An assortment of talent takes the stage for a ...
7785   s7786  ...  Dessert wizard Adriano Zumbo looks for the nex...

[2410 rows x 12 columns]

In [105]:
movies_df["duration"].sort_values().head(20) #Aquí intenta acomodar pero como string, no como números (lexiconográfico)

463      10 min
6815    100 min
1672    100 min
7214    100 min
7208    100 min
         ...   
6848     99 min
7043     99 min
2897     99 min
4366     99 min
3622     99 min
Name: duration, Length: 5377, dtype: object

In [107]:
tvshow_df["duration"].sort_values(ascending=False)

1181    9 Seasons
5818    9 Seasons
2237    9 Seasons
468     9 Seasons
4404    9 Seasons
          ...    
4765     1 Season
4766     1 Season
4771     1 Season
4782     1 Season
3969     1 Season
Name: duration, Length: 2410, dtype: object